### ISSUE TITLE
Replay date doesn't works

### ISSUE THREAD

**Issue by campipaolo** [goggle/plugin.video.rsiplaytv#5]
Hello everyone!

I'm running addon with kodi 19.4 (token from web site) on  linux mint 19.2/libreelec 10.02/xiaomi stixk android 9/mtorola g22 android 12
The section "show per data" ("replay date) get an error "SRG SSR failed open url"
Maybe website structure has changed

Here my log file
https://paste.kodi.tv/lafaxofiwa

Thanks and sorry for my English

**Comment by goggle** [comment]
Thanks for reporting this, I'll have a look.

**Comment by campipaolo** [comment]
Thanks, great!

**Comment by goggle** [comment]
Release that fixes this issue: https://github.com/xbmc/repo-plugins/pull/4140

**Comment by campipaolo** [comment]
Thanks, It works!
